import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Chakra UI: A Comprehensive Guide",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};
export default RootLayout;
